# hello
# this my first actions workflow
name: my-actions

env:
  author: elvin

on:
  push:
    branches: 
      - main

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello World!"
        
      - name: question
        run: echo "Whats, your name?"
        
      - name: clone repo
        uses: actions/checkout@v1
        
      - name: list dir
        run: ls -la
        
  deploy_baby:
    needs: [greetings]
    runs-on: ubuntu-latest
    steps:
      - name: deploy info
        run: |
          echo 'deploy beggining'
          echo "author is ${{env.author}}"
